### ISSUE TITLE
你好,用了该类之后用不了simplepermission的类.应该是获取权限返回冲突了.

### ISSUE THREAD

**Issue by kiradan** [CaiJingLong/flutter_photo#1]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.darry.ring/com.example.flutterapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void top.kikt.imagescanner.PermissionsListener.onGranted()' on a null object reference
E/AndroidRuntime(31144): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4932)
E/AndroidRuntime(31144): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
E/AndroidRuntime(31144): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(31144): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
E/AndroidRuntime(31144): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(31144): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(31144): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/AndroidRuntime(31144): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31144): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(31144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime(31144): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void top.kikt.imagescanner.PermissionsListener.onGranted()' on a null object reference
E/AndroidRuntime(31144): 	at top.kikt.imagescanner.PermissionsUtils.dealResult(PermissionsUtils.java:204)
E/AndroidRuntime(31144): 	at top.kikt.imagescanner.ImageScannerPlugin$1.onRequestPermissionsResult(ImageScannerPlugin.kt:26)
E/AndroidRuntime(31144): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/AndroidRuntime(31144): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime(31144): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/AndroidRuntime(31144): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7843)
E/AndroidRuntime(31144): 	at android.app.Activity.dispatchActivityResult(Activity.java:7694)
E/AndroidRuntime(31144): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4928)
E/AndroidRuntime(31144): 	... 9 more

**Comment by CaiJingLong** [comment]
目测是 [photo_manager](https://github.com/CaiJingLong/flutter_photo_manager) 部分引发的权限相关的问题

**Comment by CaiJingLong** [comment]
fixed
