### ISSUE TITLE
System settings do not open iOS

### ISSUE THREAD

**Issue by FroseMan97** [CaiJingLong/flutter_photo#113]
## Description 

The "open settings for permissions" button does not work on the iOS

## Plugin version

```
0.4.8
```

### iOS 
```
13.3
````
## Your phone info

```
iPhone X
```

**Comment by CaiJingLong** [comment]
Now, you can use `0.5.0-dev.1`.

There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.
