### ISSUE TITLE
可以加入 gif 和 图片同时选择的功能吗

### ISSUE THREAD

**Issue by leielyq** [CaiJingLong/flutter_photo#117]
可以加入 gif 和 图片同时选择的功能吗

**Comment by CaiJingLong** [comment]
Support gif.

You need to make sure your asset is in GIF format.
Select gif asset, then use originBytes or originFile to get gif image content.

**Comment by leielyq** [comment]
你好，我发现如果是gif的话，图片显示依然是静态的

**Comment by CaiJingLong** [comment]
gif does not support thumbnails.
For gif you need to use the original data, originBytes or file,

**Comment by leielyq** [comment]
好的 谢谢
