### ISSUE TITLE
[Need Help] ios编译时报关于photo_manager的错

### ISSUE THREAD

**Issue by Shirley0207** [CaiJingLong/flutter_photo#123]
## Description

项目引用了photo，android编译没问题，ios编译报错，执行pod install就会报如下错误：

[!] CocoaPods could not find compatible versions for pod "photo_manager":
  In Podfile:
    photo_manager (from `.symlinks/plugins/photo_manager/ios`)

Specs satisfying the `photo_manager (from `.symlinks/plugins/photo_manager/ios`)` dependency were found, but they required a higher minimum deployment target.

## Plugin version
版本0.4.8和0.5.0-dev.3都试过，都会报错，也单独引进过photo_manager，还是报错

**Comment by CaiJingLong** [comment]
Set your project min support sdk to iOS 9.0.

**Comment by Shirley0207** [comment]
> Set your project min support sdk to iOS 9.0.

啊，成功了！感谢大佬！
