### ISSUE TITLE
Image cropping functionality

### ISSUE THREAD

**Issue by dhruvan2912** [CaiJingLong/flutter_photo#135]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

**Describe alternatives you've considered**
Take a look at image_pickers lib 

**Additional context**
When user selects images from local storage after that add option to crop images in multiple aspects ratio and other options.

**Comment by CaiJingLong** [comment]
I think you need use [flutter_image_editor](https://github.com/fluttercandies/flutter_image_editor) .
You can see the example for editor, and use [extended_image](https://github.com/fluttercandies/extended_image)  as UI.

**Comment by dhruvan2912** [comment]
Used crop lib for cropping images after picked.
Thanks for great library :)
