### ISSUE TITLE
第一次调用PhotoPicker.pickImage打开相册的时候很慢，第二次才会快。有没有接口可以同时选择图片和视频，如同微信那样

### ISSUE THREAD

**Issue by linguitang** [CaiJingLong/flutter_photo#14]
trans: The first call to PhotoPicker. pickImage opens the album slowly, but the second call is faster. Is there an interface to choose pictures and videos at the same time, as in Wechat?

**Comment by CaiJingLong** [comment]
The first time you open it, you need to scan the information anyway. The next time you open it, it's faster because of the caching.
This method is due to historical reasons, no renaming, in fact, you can choose both pictures and videos at the same time.

**Comment by CaiJingLong** [comment]
I will add a badge with thumb item to help users identify pictures or videos

**Comment by linguitang** [comment]
thanks！
