### ISSUE TITLE
add a video badge to help user know video or photo

### ISSUE THREAD

**Issue by CaiJingLong** [CaiJingLong/flutter_photo#15]

**Comment by CaiJingLong** [comment]
finish in #16

**Comment by linguitang** [comment]
video mark as Icons.videocam icon  and video duration text will be better

**Comment by CaiJingLong** [comment]
Another badge is duration. Or you can create a BadgeDelegate to custom your video badge.

https://github.com/CaiJingLong/flutter_photo/blob/46a3e78b3824a2da38cc0e8ea646fcfe7dbc1fca/lib/src/delegate/badge_delegate.dart#L46

**Comment by linguitang** [comment]
good! thanks!
