### ISSUE TITLE
How to Change Language?

### ISSUE THREAD

**Issue by chintooflutter** [CaiJingLong/flutter_photo#20]
I am new student to learn flutter. 

Can you add codes or guides in your documentation files where i can change the language from Chinese to English?

Thank you for making great project!

**Comment by CaiJingLong** [comment]
See readme.

![image](https://user-images.githubusercontent.com/14145407/51656641-d64ac000-1fdc-11e9-8c4b-b8f2cd8325f4.png)

You can use `provider` param to change language.

**Comment by chintooflutter** [comment]
![gihub - flutter photo error](https://user-images.githubusercontent.com/46987072/51657629-78fa4300-1fcb-11e9-9802-f463cd131b65.JPG)


I have change the code. Like as follow.
provider: I18nProvider.english,

But from above screen shot showing me Chinese languge, i have make black round on that.

**Comment by CaiJingLong** [comment]
Bottom left is album name, this is seem a bug. I will fixed it.

**Comment by CaiJingLong** [comment]
fixed it.
update versioin to 0.1.9
