### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by fantasyStyle** [CaiJingLong/flutter_photo#22]
```bash
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building ConfigProvider:
flutter: inheritFromWidgetOfExactType(ConfigProvider) or inheritFromElement() was called before
flutter: _PhotoMainPageState.initState() completed.
flutter: When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
flutter: widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
flutter: or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
flutter: inherited widget.
flutter: Typically references to to inherited widgets should occur in widget build() methods. Alternatively,
flutter: initialization based on inherited widgets can be placed in the didChangeDependencies method, which
flutter: is called after initState and whenever the dependencies change thereafter.
```
![simulator screen shot - iphone x - 2019-01-31 at 10 39 16](https://user-images.githubusercontent.com/16890525/52026955-ab182180-2544-11e9-8160-1bafddda1f41.png)

**Comment by fantasyStyle** [comment]
photo: ^0.1.9 , flutter 1.1.9 , iPhoneX

**Comment by CaiJingLong** [comment]
Can you provide a minimum runnable code?
I haven't seen this problem before.

**Comment by fantasyStyle** [comment]
是这样的  引入该插件后 我完全复制main.dart 到我的程序中

**Comment by CaiJingLong** [comment]
Clone the repo.
Try to run example.
If it happen error, copy the error log into the comment.

**Comment by fantasyStyle** [comment]
我下载该程序 直接运行也是同样的错误

**Comment by CaiJingLong** [comment]
@fantasyStyle  thx for use.
update to version 0.1.10

**Comment by fantasyStyle** [comment]
现在可以了，谢谢

**Comment by CatEatFishs** [comment]
你好 我也遇到了这个问题，dart 2.1.1 flutter 1.1.8 photo:0.2.0  ,打开相册就报这个错误,有的手机没问题，华为 HonorPlay, Android 9.0 会报错，我试了华为另一款9.0手机没问题，怀疑是机型的问题，您看能不能让代码更兼容一些机型

**Comment by CaiJingLong** [comment]
@CatEatFishs  Please provide a complete log on 0.2.0 to help me solve this problem.

**Comment by CaiJingLong** [comment]
UI code is developed using flutter, and there is no compatibility problem in theory.
I will close the issue first, and if the same problem arises later, I will reopen the issue.
