### ISSUE TITLE
How to sort by time

### ISSUE THREAD

**Issue by CatEatFishs** [CaiJingLong/flutter_photo#28]
How to sort by time？
如何按照时间顺序，最新的照片在第一张显示

**Comment by CaiJingLong** [comment]
There is a problem with the sorting of this version, and I will fix it in the next version.

**Comment by CatEatFishs** [comment]
now, I'm looking at your code,
abstract class SortDelegate {
  const SortDelegate();

  void sort(List<AssetPathEntity> list);

  static const none = DefaultSortDelegate();

  static const common = CommonSortDelegate();
}

class DefaultSortDelegate extends SortDelegate {
  const DefaultSortDelegate();

  @override
  void sort(List<AssetPathEntity> list) {}
}

class CommonSortDelegate extends SortDelegate {
  const CommonSortDelegate();

  @override
  void sort(List<AssetPathEntity> list) {
    list.sort((path1, path2) {
      if (path1.isAll) {
        return -1;
      }

      if (path2.isAll) {
        return 1;
      }

      if (_isCamera(path1)) {
        return -1;
      }

      if (_isCamera(path2)) {
        return 1;
      }

      if (_isScreenShot(path1)) {
        return -1;
      }

      if (_isScreenShot(path2)) {
        return 1;
      }

      return otherSort(path1, path2);
    });
  }

  int otherSort(AssetPathEntity path1, AssetPathEntity path2) {
    return path1.name.compareTo(path2.name);
  }

  bool _isCamera(AssetPathEntity entity) {
    return entity.name.toUpperCase() == "camera".toUpperCase();
  }

  bool _isScreenShot(AssetPathEntity entity) {
    return entity.name.toUpperCase() == "screenshots".toUpperCase() || entity.name.toUpperCase() == "screenshot".toUpperCase();
  }
}
///////////////////////
i don't konw this how to sort ,example return -1,

**Comment by CaiJingLong** [comment]
This sort is between `AssetPathEntity`.

This sort is between `AssetPathEntity`, such as letting Recent be in the front, taking pictures in the second, screenshots in the third, and other sort by natural subheadings.

`AssetEntity` sorting is not currently done.
1,0 or 1 of sort. You need to see `List.sort` document.

**Comment by CatEatFishs** [comment]
Thanks, Looking forward to the next version

**Comment by CaiJingLong** [comment]
Fixed this problem on the master branch.
Please wait for the next release.
