### ISSUE TITLE
HDR格式图片支持

### ISSUE THREAD

**Issue by fantasyStyle** [CaiJingLong/flutter_photo#36]
选中HDR格式的图片，退出该组件后用FileImage(File(path)),无法显示，error： Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
![simulator screen shot - iphone x - 2019-03-06 at 17 19 39](https://user-images.githubusercontent.com/16890525/53870463-3c435200-4035-11e9-92de-41f7d7815f7b.png)

**Comment by CaiJingLong** [comment]
Can you provide some `HDR` image to me.
I try to support it.

**Comment by fantasyStyle** [comment]
这个图片是iPhone 模拟器自带的，或者你可以使用iPhone拍照HDR

**Comment by CaiJingLong** [comment]
Try do:

1. open flutter application with simulator.
2. pick HDR file.
3. print file path to console.
4. copy file from path.
5. upload file to issue or send email to me cjl_spy@163.com

----

I try to locate and solve problem.

**Comment by CaiJingLong** [comment]
OK, I'll fix this in the next version.

**Comment by fantasyStyle** [comment]
非常感谢

**Comment by CaiJingLong** [comment]
update version to 0.3.2
