### ISSUE TITLE
[Feature]Add a branch not use AndroidX

### ISSUE THREAD

**Issue by Wujerry** [CaiJingLong/flutter_photo#38]
Do you have time to add a branch that not use AndroidX
I had use some plugins haven`t support AndroidX

**Comment by CaiJingLong** [comment]
you just see [gitbook](https://caijinglong.gitbooks.io/migrate-flutter-to-androidx/content/)

Gradle will help you make compatibility with other libraries that do not support andoridX and ensure that your project runs.

**Comment by CaiJingLong** [comment]
Look at the document: https://github.com/CaiJingLong/flutter_photo#migrate-to-androidx.

**Comment by Wujerry** [comment]
thx, I have already upgrade all my plugin to AndroidX, and they works great!

**Comment by CaiJingLong** [comment]
Follow the plan provided by Google to migrate. Even if your upstream plugin does not complete the migration, the gradle plugin will help you run the project.
