### ISSUE TITLE
 AndroidX incompatibilities in this Flutter app

### ISSUE THREAD

**Issue by JerryNingZhen** [CaiJingLong/flutter_photo#39]
AndroidX incompatibilities in this Flutter app

* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 13s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        13.7s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_photo#migrate-to-androidx
