### ISSUE TITLE
小米手机授权通过

### ISSUE THREAD

**Issue by chenxinfei2014** [CaiJingLong/flutter_photo#49]
选择系统相册就奔溃

**Comment by CaiJingLong** [comment]
My device is MI 8, I don't seem the problem.

Please post your crash log and minimum runnable code to there.

---

And please add `flutter doctor -v` to there.

**Comment by chenxinfei2014** [comment]
这个漏加了，现在可以了
rootProject.allprojects {
    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.github.bumptech.glide'
                        && details.requested.name.contains('glide')) {
                    details.useVersion "4.8.0"
                }
            }
        }
    }
}
