### ISSUE TITLE
您好，checkbox大小可以配置吗，感觉太容易触摸到预览了

### ISSUE THREAD

**Issue by yunnian** [CaiJingLong/flutter_photo#52]
您好，checkbox大小可以配置吗，感觉太容易触摸到预览了

**Comment by CaiJingLong** [comment]
这个目前不能配置

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/62924615-09229d00-bde3-11e9-9cea-53585be09aa6.png)
You can use the property to create your widget.
