### ISSUE TITLE
Use the latest photo_manager's paging to refactor the code.

### ISSUE THREAD

**Issue by CaiJingLong** [CaiJingLong/flutter_photo#58]

**Comment by zzpmaster** [comment]
hi，请问在icloud的图片可以正常显示吗，photo_manager 0.3.5版本

**Comment by CaiJingLong** [comment]
> hi，请问在icloud的图片可以正常显示吗，photo_manager 0.3.5版本

This icloud problem should have been fixed in photo_manager 0.3.5.
You can use it.
```
photo_manager : ^0.3.5
photo: ^0.3.4+1
```

Photo_manager version 0.4.0 is being refactored
The latest version of photo will also be followed by photo_manager changes in the recent period.

The photo_manager version 0.4.0 link caijinglong/flutter_photo_manager#102

**Comment by zzpmaster** [comment]
ok, thanks
