### ISSUE TITLE
Video picker problem (android)

### ISSUE THREAD

**Issue by farrelanelca** [CaiJingLong/flutter_photo#59]
![Screenshot_2019-09-08-13-00-06-036_com miui gallery](https://user-images.githubusercontent.com/42790915/64484190-e5634300-d238-11e9-904c-19ddce195eff.png)
![Screenshot_2019-09-08-12-59-51-812_com example example](https://user-images.githubusercontent.com/42790915/64484191-e5fbd980-d238-11e9-9c61-62cabfc6c452.png)

in iphone work, but in android not work

**Comment by CaiJingLong** [comment]
Can you try to use the latest version 0.4.1+1?

**Comment by farrelanelca** [comment]
let me try

**Comment by farrelanelca** [comment]
there stil error

`E/flutter ( 3947): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'index' was called on null.
E/flutter ( 3947): Receiver: null
E/flutter ( 3947): Tried calling: index
E/flutter ( 3947): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 3947): #1      PhotoManager.getAssetPathList (package:photo_manager/src/manager.dart:32:18)
E/flutter ( 3947): <asynchronous suspension>
E/flutter ( 3947): #2      _PhotoMainPageState._refreshListFromGallery (package:photo/src/ui/page/photo_main_page.dart:221:39)
E/flutter ( 3947): <asynchronous suspension>
E/flutter ( 3947): #3      _PhotoMainPageState._refreshList (package:photo/src/ui/page/photo_main_page.dart:196:5)
E/flutter ( 3947): #4      _PhotoMainPageState.initState (package:photo/src/ui/page/photo_main_page.dart:84:5)
E/flutter ( 3947): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 3947): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 3947): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 3947): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 3947): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 3947): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 3947): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 3947): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 3947): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 3947): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 3947): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 3947): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 3947): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 3947): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 3947): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 3947): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 3947): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 3947): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 3947): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 3947): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 3947): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 3947): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 3947): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 3947): #44     ComponentElement._firstBuild (package:flutter/src/widgets/`

**Comment by CaiJingLong** [comment]
Can you try to use version 0.4.7?

**Comment by dvasea1** [comment]
The same for me: on android i don't see my videos

**Comment by dvasea1** [comment]
@CaiJingLong can you check please?

**Comment by dvasea1** [comment]
@CaiJingLong can't see videos. Can help please?

**Comment by dvasea1** [comment]
Need help. Can't pick video

**Comment by CaiJingLong** [comment]
@dvasea1 
Can you add 

```yaml
  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: 30b8b79fb44ee403e5a8e1c30aad5fe1c00581a3
```

to your pubspec.yaml and test?

**Comment by dvasea1** [comment]
> @dvasea1
> Can you add
> 
> ```yaml
>   photo_manager:
>     git:
>       url: https://github.com/CaiJingLong/flutter_photo_manager.git
>       ref: 30b8b79fb44ee403e5a8e1c30aad5fe1c00581a3
> ```
> 
> to your pubspec.yaml and test it?

@CaiJingLong very good. let me know when you will do a new version please.

**Comment by CaiJingLong** [comment]
@dvasea1 
The commit resolved your problem ?

**Comment by dvasea1** [comment]
@CaiJingLong yes. Now can see video from Android. I forked your project "photo" and changed "photo_manager" inside project.

**Comment by CaiJingLong** [comment]
Thx for test.

After completing some fixes, I will update the new version, it will take a few days.

**Comment by CaiJingLong** [comment]
Now, you can use `0.5.0-dev.1`.

There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.
