### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by malikdoksoz** [CaiJingLong/flutter_photo#62]
`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: inheritFromWidgetOfExactType(PhotoPickerProvider) or inheritFromElement() was called before _PhotoMainPageState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.`

after click _testPhotoListParams function on iOS and preview not working. First he lists the old photos. Old to new. How can i order by new to old.

Another Bug after select photo
`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type '_Uint8ArrayView' is not a subtype of type 'String'
`
<img width="638" alt="Ekran Resmi 2019-09-13 18 27 37" src="https://user-images.githubusercontent.com/26676061/64874695-3d90af80-d654-11e9-816a-02f78c8835e7.png">

Another bug

`Unhandled Exception: NoSuchMethodError: The getter 'index' was called on null.
`

**Please try this library example with version 0.4.0. You will see errors.**

**Comment by CaiJingLong** [comment]
Does this problem occur in ios or android?

**Comment by malikdoksoz** [comment]
iOS. I used the example(directory) codes of this library.

**Comment by CaiJingLong** [comment]
Thx, I will fix it.

**Comment by malikdoksoz** [comment]
Thank you sir, I am waiting new version. After release please update example directory.

**Comment by CaiJingLong** [comment]
Fixed in https://github.com/CaiJingLong/flutter_photo_manager/pull/109

**Comment by CaiJingLong** [comment]
Update version to 0.4.2.
