### ISSUE TITLE
The method '_mulFromInteger' was called on null.

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo#66]
Hi,
I'm using the library in this way:
1. I get the list of folder with 
`List<AssetPathEntity> pathList = await PhotoManager.getImageAsset();`
2. I save the ID of some pics in a database
```
for (AssetEntity pic in pathList.first) {
  String id=pic.id; 
  //then save id on the db
}
```
3. In another part of the app, I read the IDs from the db and I try to display the pic using the AssetEntity:
```
String picID= /*read from db*/;
Container(
          child: ImageItem(
            entity: new AssetEntity(id: picID),
            size: widget.picSize, //dynamic size
            loadingDelegate: DefaultLoadingDelegate(),
            badgeDelegate: DefaultBadgeDelegate(),
          )
)
```

Then I get this error:
```
The method '_mulFromInteger' was called on null.
Receiver: null
Tried calling: _mulFromInteger(1000000)
```
that is proprably from the method   `Widget _buildImageItem(BuildContext context, Uint8List data)` in `image_item.dart` from the line:
```
final badgeBuilder = badgeDelegate?.buildBadge(context, entity.type, entity.videoDuration);
```

Maybe a possible fix is in entity.dart:
`Duration get videoDuration => Duration(seconds: duration ?? 0);`

What do you think?

**Comment by CaiJingLong** [comment]
Thx for pr. I merged PR to master, so I'll close the issue.
