### ISSUE TITLE
出现了Native 方法错误

### ISSUE THREAD

**Issue by liuchuancong** [CaiJingLong/flutter_photo#67]
E/MethodChannel#top.kikt/photo_manager(17445): java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.bumptech.glide.Glide.get(Glide.java:168)
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.bumptech.glide.Glide.with(Glide.java:716)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.thumb.ThumbnailUtil.getThumbnailByGlide(ThumbnailUtil.kt:22)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.core.PhotoManager.getThumb(PhotoManager.kt:78)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1.onGranted(PhotoManagerPlugin.kt:149)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:111)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:84)
E/MethodChannel#top.kikt/photo_manager(17445): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:227)
E/MethodChannel#top.kikt/photo_manager(17445): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#top.kikt/photo_manager(17445): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#top.kikt/photo_manager(17445): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#top.kikt/photo_manager(17445): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#top.kikt/photo_manager(17445): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#top.kikt/photo_manager(17445): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#top.kikt/photo_manager(17445): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#top.kikt/photo_manager(17445): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#top.kikt/photo_manager(17445): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
I/zygote64(17445): Do partial code cache collection, code=250KB, data=151KB
I/zygote64(17445): After code cache collection, code=250KB, data=151KB
I/zygote64(17445): Increasing code cache capacity to 1024KB

**Comment by CaiJingLong** [comment]
Can you provide an example to reproduce it?

**Comment by liuchuancong** [comment]
就是一打开就会出现，但是运行demo没问题。

**Comment by liuchuancong** [comment]
自己实例化了一个GlideApp 还是会蹦

**Comment by liuchuancong** [comment]
不好意思， <meta-data
            android:name="com.netease.nim.uikit.support.glide.NIMGlideModule"
            android:value="GlideModule"/> 加了一行这个没看到错误原因，打扰了

**Comment by liuchuancong** [comment]
<meta-data
            android:name="com.netease.nim.uikit.support.glide.NIMGlideModule"
            android:value="GlideModule"/>
