### ISSUE TITLE
升级到安卓x之后视频一直在loading

### ISSUE THREAD

**Issue by atheist1** [CaiJingLong/flutter_photo#81]
升级到安卓x之后视频一直在loading
![image](https://user-images.githubusercontent.com/27856388/69396338-e3c7f800-0d1c-11ea-9861-ac927f70f148.png)

![image](https://user-images.githubusercontent.com/27856388/69396353-ec203300-0d1c-11ea-85d4-0e9087fde06a.png)

**Comment by CaiJingLong** [comment]
link to https://github.com/CaiJingLong/flutter_photo_manager/issues/129

**Comment by CaiJingLong** [comment]
fixed by CaiJingLong/flutter_photo_manager#130

**Comment by atheist1** [comment]
> Fixed in [CaiJingLong/flutter_photo_manager#130](https://github.com/CaiJingLong/flutter_photo_manager/pull/130)

请问下最新版本的photo_manager更新到flutter package pub上了吗，我用flutter packages get photo这个插件好像还是0.4.4的版本

**Comment by CaiJingLong** [comment]
I will push new version in few hours.

**Comment by pheromone** [comment]
@atheist1  你使用0.4.5是可以么?我的还是一直转圈
