### ISSUE TITLE
currentPath 是 null

### ISSUE THREAD

**Issue by Jokergz** [CaiJingLong/flutter_photo#82]
这个是怎么回事，以及我这边怎么解决才会显示中文？

![794E5836-5BEA-4322-BD32-C4EA27EE8800](https://user-images.githubusercontent.com/58164167/70487634-f0c45400-1b30-11ea-903b-162e10c187fb.png)
![031EE840-68AA-4C2D-9A2E-002E436471C8](https://user-images.githubusercontent.com/58164167/70487635-f15cea80-1b30-11ea-9b56-2986fb2d394d.png)

**Comment by minr** [comment]
同问。

**Comment by CaiJingLong** [comment]
And example to reproduce it?

**Comment by taosimple** [comment]
photo_main_page.dart _onGalleryChange 方法改成这样：
`void _onGalleryChange(AssetPathEntity assetPathEntity) async {
     _currentPath = assetPathEntity;
     scrollController.jumpTo(0.0);

    // _currentPath.assetList.then((v) async {
    //   _sortAssetList(v);
    //   list.clear();
    //   list.addAll(v);
    //   scrollController.jumpTo(0.0);
    //   await checkPickImageEntity();
    //   setState(() {});
    // });
    if (assetPathEntity != assetProvider.current) {
      assetProvider.current = assetPathEntity;
      await assetProvider.loadMore();
      setState(() {});
    }
  }`
