### ISSUE TITLE
Pictures downloaded with flutter_downloader or image_downloader not shown

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo#85]
Hi,
I'm using your plugin and I've noticed this strange behaviour: if I download a picture from the internet inside the app using either **image_downloader** or **flutter_downloader** library, I see the file in the Downloads folder but not in your picker. I noticed that if I manually rename the files using the File Manager, then they appear.

How can this happen?

Thanks

**Comment by CaiJingLong** [comment]
The data sources of this library are PHPhoto (ios) and MediaStore (android).
Which may be caused by your operation triggering an update of these data sources by the system itself.

**Comment by rignaneseleo** [comment]
So in your opinion flutter_downloader doesn't trigger them?

**Comment by rignaneseleo** [comment]
I opened an issue on the other side: https://github.com/fluttercommunity/flutter_downloader/issues/202

**Comment by CaiJingLong** [comment]
I don't know how to trigger this operation in ios.

In Android, if an item is inserted using the MediaStore API, this refresh action will be triggered.
There are two other ways to trigger it.
- Broadcast
- MediaScannerConnection

**Comment by rignaneseleo** [comment]
How can I manually add a picture to the recentpic list?

**Comment by rignaneseleo** [comment]
I solved it using my plugin: https://pub.dev/packages/gallerytrigger
