### ISSUE TITLE
Please fill _assetExistsWithId method

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo#91]
At the moment if I do this:
```
var  a = new AssetEntity(id: _resourceID); 
return a.exists;
```
I always get true because in PhotoManager I have:
```
  static Future<bool> _assetExistsWithId(String id) async {
    return true;
  }
```

Can you please make it work? It is a big defect expecially for iOS where the workaround of getting the file and check its existance is really slow.

Thanks

**Comment by CaiJingLong** [comment]
I will implement it as soon as possible.

**Comment by CaiJingLong** [comment]
I implement it in [manager-commit](https://github.com/CaiJingLong/flutter_photo_manager/commit/2e23de5d0c3ef4b7c296c34323c78c03f07e483b).

**Comment by rignaneseleo** [comment]
Great! When will it be available in the production version here?

**Comment by CaiJingLong** [comment]
I've been working on another open source library recently.
But there are some problems with this library. I also need to adjust. The plan of this library is about 3 to 5 days.
