### ISSUE TITLE
Null exception for Android 10 user

### ISSUE THREAD

**Issue by a27919478** [CaiJingLong/flutter_photo#93]
![image](https://user-images.githubusercontent.com/19726808/72213072-89306880-3523-11ea-8557-c6281eb6c59e.png)
Please take a look at this problem.

**Comment by CaiJingLong** [comment]
It looks like your project uses R8 / Proguard, you may need to restore this part of the code using mapping, and then send the log here.

![image](https://user-images.githubusercontent.com/14145407/72229354-f1954d80-35e8-11ea-977e-3f066dd9a094.png)

Also, how you use this library may require some code snippets to let me know how to reproduce this problem.

**Comment by a27919478** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/19726808/72229645-2bffea00-35eb-11ea-9d38-63286804c5d2.png">
![image](https://user-images.githubusercontent.com/19726808/72229684-71bcb280-35eb-11ea-8bb1-316927ef23c3.png)
I suspect that null value is not allowed as return value in getString method.

**Comment by CaiJingLong** [comment]
Now, you can use `0.5.0-dev.1`.

There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.
